name: DELETE STALE BRANCH

on:
  push:
    branches:
      - 'test/branch'
  workflow_dispatch:
    inputs: {}

permissions:
  contents: write

jobs:
  delete-stale-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetches all branches

      - name: Fetch all branches
        run: git fetch --all

      - name: Get list of all branches
        run: |
          branches=$(git branch -r | grep -v '\->' | sed 's/origin\///')
          echo "Branches: $branches"
          echo "$branches" > branches.txt

      - name: Check for Stale Branches
        run: |
          echo "Checking for branches with no commits in the last 60 days..."
          stale_branches=()
          current_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          sixty_days_ago=$(date -u -d "-60 days" +%Y-%m-%dT%H:%M:%SZ)

          echo "Current date: $current_date"
          echo "Date 60 days ago: $sixty_days_ago"

          for branch in $(cat branches.txt); do
            if git rev-parse --verify origin/$branch >/dev/null 2>&1; then
              recent_commit_date=$(git log -1 --format=%cI origin/$branch)
              echo "Branch: $branch, Recent commit date: $recent_commit_date"
              if [[ "$branch" != "main" && "$recent_commit_date" < "$sixty_days_ago" ]]; then
                stale_branches+=($branch)
              fi
            else
              echo "Branch $branch does not exist."
            fi
          done
          if [ ${#stale_branches[@]} -eq 0 ]; then
            echo "No branches are stale."
          else
            echo "Stale branches found:"
            count=1
            for branch in "${stale_branches[@]}"; do
              echo "$count. $branch"
              count=$((count + 1))
              echo "Deleting branch: $branch"
              git push origin --delete "$branch"
            done
          fi

      # - name: Delete Stale Branches
      #   run: |
      #     for branch in "${stale_branches[@]}"; do
      #       echo "Deleting branch: $branch"
      #       git push origin --delete "$branch"
      #     done
